### ISSUE TITLE
Not exactly and issue but a question,  will this work on a modded Xbox360?

### ISSUE THREAD

**Issue by danielius200629** [marty28/Half-LifeX#10]
The tittle explains everything, I want to play this game on my RGH modded Xbox 360, will it work?

**Comment by szymmirr** [comment]
I tested it. Both 64 and 128 MB versions crash on Xbox logo

**Comment by danielius200629** [comment]
> I tested it. Both 64 and 128 MB versions crash on Xbox logo

😥 Thank you for tye response
